### ISSUE TITLE
No way to clear the watches set by the ew command in the debugger

### ISSUE THREAD

**Issue by ogarvey** [cdifan/cdiemu#12]
Believe I mentioned this one on Discord a while back but it's just bitten me again so thought I'd best open an issue at the least.

To reproduce, open a title (this was Laser Lords), and start playing. Then open the debugger and add a watch with e.g. `ew 26662c`

When the method is called by the game code, the debugger pauses as expected but because in this instance it's a method that fires constantly (handles pointer input), to do anything else I then have to close the emulator and reload the game.

**Comment by cdifan** [comment]
Fixed by the following commit:

Author: CD-i Fan <cdifan@gmail.com>
Date:   Sat Aug 5 01:30:45 2023 +0200

    Add debugger ewk [ADDR|*] command to kill watch addresses
